### ISSUE TITLE
Token issues

### ISSUE THREAD

**Issue by MaxXor** [ethcore/parity#3326]
Whenever I access http://127.0.0.1:8180 I always have to enter some tokens since 1.4.0 (it was fine before :/ ).

1. It's a pain on Windows to read them manually from the console window and type them in the browser. Could you at least write them in a new line so it's easier to copy?
2. Is there a way to disable the tokens?
3. Can you make the tokens contain not 0's or O's. It's hard to tell which one is the right one.
4. Can you save the tokens in a browser cookie so I don't have to enter again when refreshing the site?

**Comment by tomusdrw** [comment]
This is a known issue fixed in `1.4.1` hotfix release. Please update and let us know if it happens again for you.

**Comment by MaxXor** [comment]
Ehm, I'm using 1.4.1.

**Comment by jacogr** [comment]
Really sorry about that, the 1.4.1 fix was not done 100% - we have 1.4.2 in final QA, and this time making sure we don't rush a fix and not having it 100%. Bear with us just for today.

**Comment by MaxXor** [comment]
Thanks. :)

**Comment by MaxXor** [comment]
Sorry to say this, but it's still not working correctly in 1.4.2. I have to copy the token from console in two parts because it's not in a new line.... So I paste the first part and then the second. What happens? Nothing, it just resets the textfield and i have to enter it again. I couldn't get it right after 4 tries.... :/
